port: 7000

oauthStateString: "state"
google:
  clientID: "191076122341-oi0pdhcii14s5mgjuc1k42to6at05jcb.apps.googleusercontent.com"
  clientSecret: "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"
#google:
#  clientID: "310693608106-6crvhutbh6kpjmt6n05lsdi3v6js6vvd.apps.googleusercontent.com"
#  clientSecret: "UINmn0D6Vab16Ov84pRBqRsc"
